In [1]:
import tensorflow as tf


In [2]:
a = tf.constant([
    [
        [1.0,2.0,3.0,4.0],
        [5.0,6.0,7.0,8.0],
        [8.0,7.0,6.0,5.0], 
        [4.0,3.0,2.0,1.0]
    ],
    [
        [4.0,3.0,2.0,1.0],
        [8.0,7.0,6.0,5.0],
        [1.0,2.0,3.0,4.0], 
        [5.0,6.0,7.0,8.0]
    ]
])


In [3]:
print(a)

Tensor("Const:0", shape=(2, 4, 4), dtype=float32)


In [4]:
print(dir(a
         ))

['OVERLOADABLE_OPERATORS', '__abs__', '__add__', '__and__', '__array_priority__', '__bool__', '__class__', '__delattr__', '__dict__', '__div__', '__doc__', '__eq__', '__floordiv__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__gt__', '__hash__', '__init__', '__invert__', '__iter__', '__le__', '__lt__', '__matmul__', '__mod__', '__module__', '__mul__', '__neg__', '__new__', '__nonzero__', '__or__', '__pow__', '__radd__', '__rand__', '__rdiv__', '__reduce__', '__reduce_ex__', '__repr__', '__rfloordiv__', '__rmatmul__', '__rmod__', '__rmul__', '__ror__', '__rpow__', '__rsub__', '__rtruediv__', '__rxor__', '__setattr__', '__sizeof__', '__str__', '__sub__', '__subclasshook__', '__truediv__', '__weakref__', '__xor__', '_add_consumer', '_as_node_def_input', '_as_tf_output', '_consumers', '_dtype', '_handle_dtype', '_handle_shape', '_op', '_override_operator', '_shape', '_shape_as_list', '_value_index', 'consumers', 'device', 'dtype', 'eval', 'get_shape', 'graph', 'name', 'op'

In [5]:
sess = tf.Session()
sess.run(a
        )

array([[[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 8.,  7.,  6.,  5.],
        [ 4.,  3.,  2.,  1.]],

       [[ 4.,  3.,  2.,  1.],
        [ 8.,  7.,  6.,  5.],
        [ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.]]], dtype=float32)

In [8]:
a = tf.reshape(a,[1,4,4,2])


In [9]:
sess.run(a
    )

array([[[[ 1.,  2.],
         [ 3.,  4.],
         [ 5.,  6.],
         [ 7.,  8.]],

        [[ 8.,  7.],
         [ 6.,  5.],
         [ 4.,  3.],
         [ 2.,  1.]],

        [[ 4.,  3.],
         [ 2.,  1.],
         [ 8.,  7.],
         [ 6.,  5.]],

        [[ 1.,  2.],
         [ 3.,  4.],
         [ 5.,  6.],
         [ 7.,  8.]]]], dtype=float32)

In [10]:
a.shape

TensorShape([Dimension(1), Dimension(4), Dimension(4), Dimension(2)])

In [16]:
pooling = tf.nn.max_pool(a, [1,2,2,1],[1,1,1,1], padding='VALID')


In [17]:
sess.run(pooling)

array([[[[ 8.,  7.],
         [ 6.,  6.],
         [ 7.,  8.]],

        [[ 8.,  7.],
         [ 8.,  7.],
         [ 8.,  7.]],

        [[ 4.,  4.],
         [ 8.,  7.],
         [ 8.,  8.]]]], dtype=float32)

In [13]:
sess.run(a)

array([[[[ 1.,  2.],
         [ 3.,  4.],
         [ 5.,  6.],
         [ 7.,  8.]],

        [[ 8.,  7.],
         [ 6.,  5.],
         [ 4.,  3.],
         [ 2.,  1.]],

        [[ 4.,  3.],
         [ 2.,  1.],
         [ 8.,  7.],
         [ 6.,  5.]],

        [[ 1.,  2.],
         [ 3.,  4.],
         [ 5.,  6.],
         [ 7.,  8.]]]], dtype=float32)

In [18]:
pooling_n = tf.nn.max_pool(a,[1,2,2,1],[1,2,2,1],padding='VALID')


In [19]:
sess.run(pooling_n)

array([[[[ 8.,  7.],
         [ 7.,  8.]],

        [[ 4.,  4.],
         [ 8.,  8.]]]], dtype=float32)

厉害!